name: my_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  dio: ^4.0.4
  json_annotation: ^4.1.0
  retrofit: ^2.0.1
  flutter_simple_dependency_injection: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.1
  retrofit_generator: ^2.0.0
  json_serializable: ^5.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

